# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orca < Formula
  desc "Docker Compose TUI manager"
  homepage "https://github.com/r7sqtr/orca"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.0/orca_0.1.0_darwin_amd64.tar.gz"
      sha256 "39abaaf3226ea9b2b564cdf6fb68814c5cea2e8d3b0aa3731596f39ddac1abcc"

      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.0/orca_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba85a3a12e9e80d986b473fad1a295e830a96f3c7d9ff92948a1806720459919"

      define_method(:install) do
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.0/orca_0.1.0_linux_amd64.tar.gz"
      sha256 "f0b0377d523e617b80ac263ffca61a24c09a1fcc7c552ec26f199916b12cc686"
      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.0/orca_0.1.0_linux_arm64.tar.gz"
      sha256 "2e5d04158d9f740632241d071c612e8b0aa2027225154c992674882691df6a4c"
      define_method(:install) do
        bin.install "orca"
      end
    end
  end
end
