# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrcaTui < Formula
  desc "Docker Compose TUI manager"
  homepage "https://github.com/r7sqtr/orca"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.7/orca_0.1.7_darwin_amd64.tar.gz"
      sha256 "7108344a84390af824443f1565dc280163075c3ce14d56d467cabdf19bcdc64e"

      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.7/orca_0.1.7_darwin_arm64.tar.gz"
      sha256 "e56fc91e3df9144e5d25af65e4d5dd13e8d386f2f121814ba09c8a5f82c7eaf3"

      define_method(:install) do
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.7/orca_0.1.7_linux_amd64.tar.gz"
      sha256 "429620ef2a01503941598297d67c77fe9cc16477215b1415afc35c56390b75dd"
      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.7/orca_0.1.7_linux_arm64.tar.gz"
      sha256 "4f52af710771c9e47d29fc5b70e7cef33027c4889e1ae16f04b8ea800e0ef33f"
      define_method(:install) do
        bin.install "orca"
      end
    end
  end
end
