# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrcaTui < Formula
  desc "Docker Compose TUI manager"
  homepage "https://github.com/r7sqtr/orca"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.8/orca_0.1.8_darwin_amd64.tar.gz"
      sha256 "1c8228186994184c1110bae935c3b18d24ab30e7a8b7765328bb8a63a3440600"

      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.8/orca_0.1.8_darwin_arm64.tar.gz"
      sha256 "79d1030fc271290962028579f68e7783ce012479591f36e7245575b3f013d405"

      define_method(:install) do
        bin.install "orca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.8/orca_0.1.8_linux_amd64.tar.gz"
      sha256 "545b7511ea70f2d008dd686002ff50586891fcf8ff82ed66ca88f1d9541b12d9"
      define_method(:install) do
        bin.install "orca"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/r7sqtr/orca/releases/download/v0.1.8/orca_0.1.8_linux_arm64.tar.gz"
      sha256 "ce1eefc769240133f7021fcd2c477cc6dbc965c2a839150e373a34b5dcb186d7"
      define_method(:install) do
        bin.install "orca"
      end
    end
  end
end
